# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: kai-scheduler
description: KAI Scheduler by NVIDIA
type: application
version: 0.0.0
appVersion: 0.0.0

dependencies:
  - name: gpu-sharing
    version: v0.1.0-alpha.1
    repository: oci://ghcr.io/kai-scheduler/gpu-sharing
    condition: global.nvFractions.set
